/* Estos son los generales no modificarlos, hacer copy y descomentar

al_car_valido('+').
al_car_valido('-').
al_car_valido('/').
al_car_valido('*').
al_car_valido('=').
al_car_valido(':').
al_car_valido('?').
al_car_valido('&').
al_car_valido('%').
al_car_valido('$').
al_car_valido('#').
al_car_valido('!').
al_car_valido('(').
al_car_valido(')').
al_car_valido('<').
al_car_valido('>').
al_car_valido('[').
al_car_valido(']').
al_car_valido('@').
al_car_valido('epsilon').
al_car_valido('num').
al_car_valido('id').
al_car_valido('eof').


al_nt_valido('A').
al_nt_valido('B').
al_nt_valido('G').
*/

al_car_valido('+').
al_car_valido('f').
al_car_valido('-').
al_car_valido('/').
al_car_valido('*').
al_car_valido(':').
al_car_valido('?').
al_car_valido('&').
al_car_valido('%').
al_car_valido('$').
al_car_valido('#').
al_car_valido('!').
al_car_valido('<').
al_car_valido('>').
al_car_valido('[').
al_car_valido(']').
al_car_valido('@').
al_car_valido('epsilon').
al_car_valido('num').
al_car_valido('id').
al_car_valido('eof').


al_nt_valido('A').
al_nt_valido('B').
al_nt_valido('C').
al_nt_valido('D').
al_nt_valido('E').
al_nt_valido('F').
al_nt_valido('G').
al_nt_valido('H').
al_nt_valido('I').
al_nt_valido('J').
al_nt_valido('K').
al_nt_valido('L').
al_nt_valido('M').
al_nt_valido('N').
al_nt_valido('O').
al_nt_valido('P').
al_nt_valido('Q').
al_nt_valido('R').
al_nt_valido('S').
al_nt_valido('T').
al_nt_valido('U').
al_nt_valido('V').
al_nt_valido('W').
al_nt_valido('X').
al_nt_valido('Y').
al_nt_valido('Z').
